plugins {
	id 'net.minecraftforge.gradle' version '[6.0,6.2)'
	id 'org.spongepowered.mixin' version '0.7.+'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = 'smoothlight-forge'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

minecraft {
	mappings channel: 'official', version: project.minecraft_version

	runs {
		client {
			workingDirectory project.file('run')
			args '-mixin.config=smoothlight.mixins.json'
			jvmArg '-Dfile.encoding=UTF-8'
			mods {
				smoothlight {
					source sourceSets.main
				}
			}
		}
		server {
			workingDirectory project.file('run')
			args '-mixin.config=smoothlight.mixins.json'
			jvmArg '-Dfile.encoding=UTF-8'
			mods {
				smoothlight {
					source sourceSets.main
				}
			}
		}
	}
}

mixin {
	add sourceSets.main, 'smoothlight.refmap.json'
	config 'smoothlight.mixins.json'
}

dependencies {
	minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
	manifest {
		attributes 'MixinConfigs': 'smoothlight.mixins.json'
	}
}

sourceSets {
	main {
		output.resourcesDir = java.destinationDirectory.get().asFile
	}
}



